config/routes.rb
  Rails.application.routes.draw do
  resources :artists

  resources :publications

  resources :poaitems

  resources :tags

  resources :poas

end

app/models/poaitem.rb
class Poaitem < ActiveRecord::Base
	has_and_belongs_to_many :poas
	has_many :artists, through: :poaitems_artists
end

app/controllers/poaitems_controller.rb
class PoaitemsController < ApplicationController
  before_action :set_poaitem, only: [:show, :edit, :update, :destroy]

  # GET /poaitems
  # GET /poaitems.json
  def index
    @poaitems = Poaitem.all
  end

  # GET /poaitems/1
  # GET /poaitems/1.json
  def show
  end

  # GET /poaitems/new
  def new
    @poaitem = Poaitem.new
  end

  # GET /poaitems/1/edit
  def edit
  end

  # POST /poaitems
  # POST /poaitems.json
  def create
    @poaitem = Poaitem.new(poaitem_params)

    respond_to do |format|
      if @poaitem.save
        format.html { redirect_to @poaitem, notice: 'Poaitem was successfully created.' }
        format.json { render :show, status: :created, location: @poaitem }
      else
        format.html { render :new }
        format.json { render json: @poaitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poaitems/1
  # PATCH/PUT /poaitems/1.json
  def update
    respond_to do |format|
      if @poaitem.update(poaitem_params)
        format.html { redirect_to @poaitem, notice: 'Poaitem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poaitem }
      else
        format.html { render :edit }
        format.json { render json: @poaitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poaitems/1
  # DELETE /poaitems/1.json
  def destroy
    @poaitem.destroy
    respond_to do |format|
      format.html { redirect_to poaitems_url, notice: 'Poaitem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poaitem
      @poaitem = Poaitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poaitem_params
      params.require(:poaitem).permit(:content, :type)
    end
end

app/helpers/poaitems_helper.rb
module PoaitemsHelper
end

app/views/poaitems/_form.html.erb
<%= form_for(@poaitem) do |f| %>
  <% if @poaitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poaitem.errors.count, "error") %> prohibited this poaitem from being saved:</h2>

      <ul>
      <% @poaitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.number_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poaitems/edit.html.erb
<h1>Editing poaitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @poaitem %> |
<%= link_to 'Back', poaitems_path %>

app/views/poaitems/index.html.erb
<h1>Listing poaitems</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @poaitems.each do |poaitem| %>
      <tr>
        <td><%= poaitem.content %></td>
        <td><%= poaitem.type %></td>
        <td><%= link_to 'Show', poaitem %></td>
        <td><%= link_to 'Edit', edit_poaitem_path(poaitem) %></td>
        <td><%= link_to 'Destroy', poaitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poaitem', new_poaitem_path %>

app/views/poaitems/new.html.erb
<h1>New poaitem</h1>

<%= render 'form' %>

<%= link_to 'Back', poaitems_path %>

app/views/poaitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @poaitem.content %>
</p>

<p>
  <strong>Type:</strong>
  <%= @poaitem.type %>
</p>

<%= link_to 'Edit', edit_poaitem_path(@poaitem) %> |
<%= link_to 'Back', poaitems_path %>